name: build and deploy app
on:
  push:
    branches:
      - build-test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'checkout branch'
        uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}

      - name: 'npm Build'
        run: |
          npm install
          npm run build

      - name: 'Deploy to S3'
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY_ID }}
          SOURCE_DIR: 'build'
